export enum ErrorCode {
  // Standard HTTP error codes
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  // Custom error codes
  VALIDATION_ERROR = "VALIDATION_ERROR",
  AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  STALE_CONNECTION = "STALE_CONNECTION",
  NETWORK_ERROR = "NETWORK_ERROR",
  BROADCAST_ERROR = "BROADCAST_ERROR",
}
